export const educations = [
    {
        id: '1',
        description: 'Studied computer science with a focus on artificial intelligence.',
        id_user: '1',
        id_level: 'level3',
        id_major: 'major1',
        id_school: 'school1',
        user: { id: '1', name: 'John Doe' },
        level: { id: 'level3', name: "Bachelor's Degree" },
        major: { id: 'major1', name: 'Computer Science' },
        school: {
            id: 'school1',
            name: 'Harvard University',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2018-08-01T00:00:00Z',
        end_at: '2022-05-15T00:00:00Z',
        level_name: "Bachelor's Degree",
        major_name: 'Computer Science',
        school_name: 'Harvard University',
    },
    {
        id: '2',
        description: 'Advanced studies in data science and machine learning.',
        id_user: '2',
        id_level: 'level4',
        id_major: 'major2',
        id_school: 'school2',
        user: { id: '2', name: 'Jane Smith' },
        level: { id: 'level4', name: "Master's Degree" },
        major: { id: 'major2', name: 'Data Science' },
        school: {
            id: 'school2',
            name: 'Stanford University',
            image: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Seal_of_Leland_Stanford_Junior_University.svg',
        },
        start_at: '2020-09-01T00:00:00Z',
        end_at: '2022-06-01T00:00:00Z',
        level_name: "Master's Degree",
        major_name: 'Data Science',
        school_name: 'Stanford University',
    },
    {
        id: '3',
        description: 'Completed a diploma program in software development.',
        id_user: '3',
        id_level: 'level2',
        id_major: 'major3',
        id_school: 'school3',
        user: { id: '3', name: 'Alice Johnson' },
        level: { id: 'level2', name: 'Diploma' },
        major: { id: 'major3', name: 'Software Development' },
        school: {
            id: 'school3',
            name: 'Technical Institute',
            image: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/Seal_of_Leland_Stanford_Junior_University.svg',
        },
        start_at: '2019-01-01T00:00:00Z',
        end_at: '2021-12-15T00:00:00Z',
        level_name: 'Diploma',
        major_name: 'Software Development',
        school_name: 'Technical Institute',
    },
    {
        id: '4',
        description: 'Earned a high school diploma with honors.',
        id_user: '4',
        id_level: 'level1',
        id_major: 'major4',
        id_school: 'school4',
        user: { id: '4', name: 'Bob Brown' },
        level: { id: 'level1', name: 'High School Diploma' },
        major: { id: 'major4', name: 'General Studies' },
        school: {
            id: 'school4',
            name: 'City High School',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2015-09-01T00:00:00Z',
        end_at: '2019-06-01T00:00:00Z',
        level_name: 'High School Diploma',
        major_name: 'General Studies',
        school_name: 'City High School',
    },
    {
        id: '5',
        description: "Pursued a Bachelor's in Business Administration.",
        id_user: '5',
        id_level: 'level3',
        id_major: 'major5',
        id_school: 'school5',
        user: { id: '5', name: 'Emily Davis' },
        level: { id: 'level3', name: "Bachelor's Degree" },
        major: { id: 'major5', name: 'Business Administration' },
        school: {
            id: 'school5',
            name: 'University of Pennsylvania',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2016-08-15T00:00:00Z',
        end_at: '2020-05-30T00:00:00Z',
        level_name: "Bachelor's Degree",
        major_name: 'Business Administration',
        school_name: 'University of Pennsylvania',
    },
    {
        id: '6',
        description: "Completed a Master's in Educational Leadership.",
        id_user: '6',
        id_level: 'level4',
        id_major: 'major6',
        id_school: 'school6',
        user: { id: '6', name: 'Michael Clark' },
        level: { id: 'level4', name: "Master's Degree" },
        major: { id: 'major6', name: 'Educational Leadership' },
        school: {
            id: 'school6',
            name: 'Columbia University',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2018-09-01T00:00:00Z',
        end_at: '2020-06-01T00:00:00Z',
        level_name: "Master's Degree",
        major_name: 'Educational Leadership',
        school_name: 'Columbia University',
    },
    {
        id: '7',
        description: 'Diploma in Graphic Design.',
        id_user: '7',
        id_level: 'level2',
        id_major: 'major7',
        id_school: 'school7',
        user: { id: '7', name: 'Sarah Wilson' },
        level: { id: 'level2', name: 'Diploma' },
        major: { id: 'major7', name: 'Graphic Design' },
        school: {
            id: 'school7',
            name: 'Art Institute',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2017-01-01T00:00:00Z',
        end_at: '2019-12-15T00:00:00Z',
        level_name: 'Diploma',
        major_name: 'Graphic Design',
        school_name: 'Art Institute',
    },
    {
        id: '8',
        description: "Bachelor's degree in Nursing.",
        id_user: '8',
        id_level: 'level3',
        id_major: 'major8',
        id_school: 'school8',
        user: { id: '8', name: 'Laura Taylor' },
        level: { id: 'level3', name: "Bachelor's Degree" },
        major: { id: 'major8', name: 'Nursing' },
        school: {
            id: 'school8',
            name: 'University of California',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2015-08-15T00:00:00Z',
        end_at: '2019-05-30T00:00:00Z',
        level_name: "Bachelor's Degree",
        major_name: 'Nursing',
        school_name: 'University of California',
    },
    {
        id: '9',
        description: "Master's degree in Public Health.",
        id_user: '9',
        id_level: 'level4',
        id_major: 'major9',
        id_school: 'school9',
        user: { id: '9', name: 'James White' },
        level: { id: 'level4', name: "Master's Degree" },
        major: { id: 'major9', name: 'Public Health' },
        school: {
            id: 'school9',
            name: 'Harvard University',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2019-09-01T00:00:00Z',
        end_at: '2021-06-01T00:00:00Z',
        level_name: "Master's Degree",
        major_name: 'Public Health',
        school_name: 'Harvard University',
    },
    {
        id: '10',
        description: 'High School Diploma.',
        id_user: '10',
        id_level: 'level1',
        id_major: 'major10',
        id_school: 'school10',
        user: { id: '10', name: 'Henry Green' },
        level: { id: 'level1', name: 'High School Diploma' },
        major: { id: 'major10', name: 'General Studies' },
        school: {
            id: 'school10',
            name: 'East High School',
            image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
        },
        start_at: '2013-09-01T00:00:00Z',
        end_at: '2017-06-01T00:00:00Z',
        level_name: 'High School Diploma',
        major_name: 'General Studies',
        school_name: 'East High School',
    },
];

export const educationDetail = {
    id: '1',
    description: 'Studied computer science with a focus on artificial intelligence.',
    id_user: '1',
    id_level: 'level3',
    id_major: 'major1',
    id_school: 'school1',
    user: { id: '1', name: 'John Doe' },
    level: { id: 'level3', name: "Bachelor's Degree" },
    major: { id: 'major1', name: 'Computer Science' },
    school: {
        id: 'school1',
        name: 'Harvard University',
        image: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Harvard_University_coat_of_arms.svg',
    },
    start_at: '2018-08-01T00:00:00Z',
    end_at: '2022-05-15T00:00:00Z',
    level_name: "Bachelor's Degree",
    major_name: 'Computer Science',
    school_name: 'Harvard University',
};
